"use client";

import { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  en: {
    headerNav1: "Home",
    headerNav2: "About",
    headerNav3: "Services",
    headerNav4: "Projects",
    headerNav5: "Testimonials",
    headerContact: "Contact",
    homeTitle: "Smarter software solutions",
    homeDesc: "We turn ideas into powerful software that makes an impact",
    scroll: "Exploring",
    bannerIntro: "INTRODUCING",
    bannerWord1: "Smarter",
    bannerWord2: "Software",
    bannerWord3: "Solutions",
    bannerButton: "Get Started",
    bannerScrolling: "Scrolling...",
    infoBar1: "Professional",
    infoBar2: "Efficient",
    infoBar3: "Trustworthy",
    homeButton: "Explore",
    aboutTitle: "About Us",
    aboutDesc:
      "DUDI Software was founded with the mission to bring the most modern technology solutions to Vietnamese businesses.",
    aboutCardTitle1: "Mission",
    aboutCardTitle2: "Vision",
    aboutCardTitle3: "Core Values",
    aboutCardDesc1:
      "Help businesses achieve successful digital transformation through strategies and optimal costs",
    aboutCardDesc2:
      "Become a leading technology company in Vietnam with international reach.",
    aboutCardDesc3: "Innovation - Superior Quality - Customer Dedication.",
    servicesTitle: "Our Services",
    servicesDesc:
      "We provide diverse technology services to meet all business needs.",
    servicesCardTitle1: "Software Development",
    servicesCardTitle2: "Mobile Application",
    servicesCardTitle3: "UI/UX Design",
    servicesCardTitle4: "Could Solutions",
    servicesCardTitle5: "AI & Machine Learning",
    servicesCardTitle6: "Technical Support",
    servicesCardDesc1:
      "Build custom software solutions tailored to each business's specific requirements.",
    servicesCardDesc2:
      "Develop mobile applications with excellent user experience.",
    servicesCardDesc3:
      "Create beautiful interfaces and optimal user experiences for your products.",
    servicesCardDesc4:
      "Consult and implement cloud systems to help businesses operate efficiently.",
    servicesCardDesc5:
      "Apply artificial intelligence to automate and optimize business processes.",
    servicesCardDesc6: "24/7 support service with experienced technical staff.",
    servicesMore: "View More",
    technologiesTitle: "Technologies We Use",
    mileStone1: "Completed projects",
    mileStone2: "Satisfied Clients",
    mileStone3: "Expert Staff",
    mileStone4: "Years of Experience",
    projectTitle: "Our Projects",
    projectDescription: "Here are some notable projects we've developed, showcasing our experience in making modern web applications",
    projectAll: "View all",
    projectCardTitle1: "Enterprise Management System",
    projectCardTitle2: "Food Delivery App",
    projectCardTitle3: "E-commerce Website",
    projectCardTitle4: "Travel review site",
    projectCardDesc1: "Web application for managing company resources.",
    projectCardDesc2: "Mobile app for ordering food from local restaurants.",
    projectCardDesc3: "Website for online shopping and product browsing.",
    projectCardDesc4: "Website for review travel locations.",
    testimonialsTitle: "Trusted by our customer",
    testimonialsCardName1: "Tran Thu Ha",
    testimonialsCardName2: "Nguyen Minh Quan",
    testimonialsCardName3: "Duong Quoc Hung",
    testimonialsCardName4: "Pham Ngoc Anh",

    TestimonialsCardTitle1: "CEO of Vincentimo",
    TestimonialsCardTitle2: "Sales Manager at Duy Nhat Tech",
    TestimonialsCardTitle3: "CTO of Duong Hung Entertainment",
    TestimonialsCardTitle4: "Founder of Young Star Academy",
    
    TestimonailsCardText1:
      "DUDI Software's services have helped us successfully digitalize. Professional team with enthusiastic support.",
    TestimonailsCardText2:
      "The application developed by DUDI has helped us increase revenue. Beautiful interface, easy to use with stable performance.",
    TestimonailsCardText3:
      "Great collaboration experience! Their engineers are skilled, communicative, and deliver on time.",
    TestimonailsCardText4:
      "We're very satisfied with the mobile app. DUDI Software truly understands user experience.",
    contactTitle: "Reach us",
    contactAddressTitle: "Address",
    contactAddress1:
      "232 Nguyen Thi Minh Khai Street, Xuan Hoa Ward, HCM City",

    contactAddress2: "49/2 Street 14, Thu Duc Ward, HCM City",
    infoTitle: "Contact",
    hourTitle: "Working Hour",
    hourText: "Monday - Friday: 9AM - 6PM",
    scanText: "Scan for quick contact",
    formInstruct:
      "Leave your information, and we will get back to you as soon as possible",
    formName: "Full Name *",
    formSubject: "Subject",
    formMessage: "Message *",
    formButton: "Submit",
    footerText:
      "Leading software company with modern, innovative technology solutions to help businesses grow sustainably.",
    footerRight: "© 2023 DUDI Software. All rights reserved.",
    footerRight1: "Privacy Policy",
    footerRight2: "Term of Use",
    portfolioDetailTitle: "Featured Project",
    portfolioButtonPrev: "Prev",
    portfolioButtonNext: "Next",
    portfolioSearch: "Search",
    projectsPageTitle: "Featured Project",
    projectsFilter: "FILTER",
    projectsSortBy: "Sort by:",
    projectsSortNewest: "Newest",
    projectsSortOldest: "Oldest",
    projectsSearchResult: "Search results:",
    projectsNoResult: "No results found for",
    projectsNoMatch: "No matching projects found",
    projectsMore: "More",
    projectsReachUs: "Reach Us",
    projectsReachSubtitle: "Leave your information, and we will get back to you as soon as possible",
    projectsScanQR: "Scan for quick contact",
    projectsName: "Name",
    projectsEmail: "Email",
    projectsSubject: "Subject",
    projectsMessage: "Message",
    // Categories
    catAll: "All",
    cat1: "E-commerce Website",
    cat2: "Enterprise Website",
    cat3: "Service Introduction Website",
    cat4: "E-commerce Platform",
    cat5: "Cosmetics Website",
    cat6: "Furniture Website",
    cat7: "Real Estate Website",
    cat8: "Restaurant Website",
    cat9: "Hotel Website",
    cat10: "Travel Website",
    cat11: "Spa & Beauty Website",
    cat12: "Clinic Website",
    cat13: "Education Website",
    cat14: "Language Center Website",
    cat15: "News & Blog Website",
    cat16: "Portfolio Website",
    cat17: "Startup Website",
    cat18: "Landing Page",
    cat19: "Event Website",
    cat20: "Recruitment Website",
    cat21: "Technology Website",
    cat22: "Phone Website",
    cat23: "Computer Website",
    cat24: "Software Website",
    // Project Titles
    projTitle1: "Yoga & Wellness Center",
    projTitle2: "SaiGonDi - Travel & Explore",
    projTitle3: "Dudi Credit - Financial Services",
    projTitle4: "MoneyWise - Expense Tracking",
    projTitle5: "Premium Restaurant System",
    projTitle6: "ANP Law Firm",
    projTitle7: "Sigma Real Estate Portal",
    projTitle8: "PC Services & Hardware Shop",
    projTitle9: "Multi-Vendor Marketplace",
    projTitle10: "Global Trading Platform",
    projTitle11: "Beauty Products Marketplace",
    projTitle12: "Skincare Store",
    projTitle13: "Furniture Store",
    projTitle14: "Home Decor Gallery",
    projTitle15: "Real Estate Portal",
    projTitle16: "Luxury Properties Finder",
    projTitle17: "Coffee Shop Management",
    projTitle18: "Specialty Coffee Hub",
    projTitle19: "Hotel Booking System",
    projTitle20: "Boutique Hotel Network",
    projTitle21: "Travel Agency Website",
    projTitle22: "Adventure Tours Booking",
    projTitle23: "Service Booking App",
    projTitle24: "Wellness Center Portal",
    projTitle25: "Medical Clinic Portal",
    projTitle26: "Dental Clinic Website",
    projTitle27: "Educational Learning Platform",
    projTitle28: "Professional Training Institute",
    projTitle29: "Language Learning Hub",
    projTitle30: "English Academy Online",
    projTitle31: "News & Blog Network",
    projTitle32: "Tech News Portal",
    projTitle33: "Portfolio Showcase",
    projTitle34: "Designer Portfolio Site",
    projTitle35: "Tech Startup Pitch",
    projTitle36: "SaaS Platform Launch",
    projTitle37: "Product Launch Landing",
    projTitle38: "Campaign Conversion Page",
    projTitle39: "Event Management Platform",
    projTitle40: "Job Portal",
    projTitle41: "Executive Search Platform",
    projTitle42: "Tech Product Showcase",
    projTitle43: "Software Solutions Hub",
    projTitle44: "Mobile Phone Store",
    projTitle45: "Computer Hardware Shop",
    projTitle46: "Software Marketplace",
    // Project Descriptions
    projDesc1: "Spa, Beauty, and Cosmetic products management system.",
    projDesc2: "Travel and exploration platform for discovering Saigon's hidden gems.",
    projDesc3: "Consumer lending and financial management platform.",
    projDesc4: "Smart personal finance and expense tracking application.",
    projDesc5: "Modern restaurant and coffee shop management solution.",
    projDesc6: "Professional legal services and law firm management platform.",
    projDesc7: "High-end real estate listings and property management system.",
    projDesc8: "E-commerce platform for computer components and hardware services.",
    projDesc9: "Platform connecting multiple sellers with buyers nationwide.",
    projDesc10: "International e-commerce platform with logistics support.",
    projDesc11: "Online store specializing in cosmetics and beauty products.",
    projDesc12: "Premium skincare brand with product recommendations.",
    projDesc13: "E-commerce platform for interior design and furniture sales.",
    projDesc14: "Curated collection of home decoration and furnishing items.",
    projDesc15: "Property listing platform with advanced search and filters.",
    projDesc16: "High-end real estate listings with virtual tours.",
    projDesc17: "POS system and customer loyalty program for cafes.",
    projDesc18: "Premium coffee roastery with online ordering system.",
    projDesc19: "Room reservation platform with guest management tools.",
    projDesc20: "Collection of luxury boutique hotels with unique experiences.",
    projDesc21: "Tourism platform with package booking and recommendations.",
    projDesc22: "Extreme sports and adventure packages with safety information.",
    projDesc23: "Complete booking system for spa and beauty services.",
    projDesc24: "Spa and wellness services with therapist profiles.",
    projDesc25: "Healthcare management system with appointment scheduling.",
    projDesc26: "Dental services platform with patient records and billing.",
    projDesc27: "Online course delivery with student progress tracking.",
    projDesc28: "Corporate training platform with certification programs.",
    projDesc29: "Foreign language training center with interactive courses.",
    projDesc30: "English language school with native speaker instructors.",
    projDesc31: "Content management system for publishing and distribution.",
    projDesc32: "Latest technology news and industry analysis platform.",
    projDesc33: "Personal portfolio website for creative professionals.",
    projDesc34: "Artistic portfolio with project galleries and client testimonials.",
    projDesc35: "Startup website with investor pitch and product demo.",
    projDesc36: "Software-as-a-service platform with free trial and pricing.",
    projDesc37: "High-converting landing page for product launches.",
    projDesc38: "Optimized landing page for marketing campaigns.",
    projDesc39: "Complete event management with ticketing and registration.",
    projDesc40: "Recruitment platform connecting employers and job seekers.",
    projDesc41: "Premium recruitment service for senior management positions.",
    projDesc42: "Product catalog for technology companies and retailers.",
    projDesc43: "Enterprise software solutions with technical documentation.",
    projDesc44: "Latest smartphones and mobile devices with specifications.",
    projDesc45: "Computer components and peripherals with tech specs.",
    projDesc46: "Digital software distribution platform with licenses.",
    recruitmentTitle: "Join Our Team",
    recruitmentDes:
      "We're looking for talented, savvy, and passionate people to join our team and help us bring modern technology solutions to businesses.",
    job1: "Full-stack Intern",
    job2: "Sales Intern",
    jobLocation1: "HCM, VietNam",
    jobLocation2: "HCM,VietNam",
    jobDesc1:
      "DUDI Software is seeking a passionate Full-stack Developer Intern to join our team. You will assist in developing both front-end and back-end features, learn modern technologies, and work alongside experienced developers on real-world projects.",
    jobDesc2:
      "DUDI Software is looking for a motivated Sales Intern to support our business development team. You will help identify potential clients, prepare presentations, assist in communication with partners, and gain hands-on experience in software sales.",
    jobButton: "Apply now",
    },
  vi: {
    headerNav1: "Trang chủ",
    headerNav2: "Về chúng tôi",
    headerNav3: "Dịch vụ",
    headerNav4: "Dự án",
    headerNav5: "Đánh giá",
    headerContact: "Liên hệ",
    homeTitle: "Giải pháp công nghệ tối ưu",
    homeDesc:
      "Chúng tôi biến ý tưởng thành phần mềm mạnh mẽ, tạo nên sự đột phá.",
    scroll: "Đang khám phá",
    bannerIntro: "GIỚI THIỆU",
    bannerWord1: "Giải pháp",
    bannerWord2: "Phần mềm",
    bannerWord3: "Thông minh",
    bannerButton: "Bắt đầu",
    bannerScrolling: "Đang cuộn...",
    homeButton: "Khám phá",
    infoBar1: "Chuyên nghiệp",
    infoBar2: "Hiệu quả",
    infoBar3: "Đáng tin cậy",
    aboutTitle: "Về Chúng Tôi",
    aboutDesc:
      "DUDI Software được thành lập với sứ mệnh mang lại những giải pháp công nghệ hiện đại nhất cho doanh nghiệp Việt Nam",
    aboutCardTitle1: "Sứ mệnh",
    aboutCardTitle2: "Tầm nhìn",
    aboutCardTitle3: "Giá trị cốt lõi",
    aboutCardDesc1:
      "Giúp doanh nghiệp một cách hiệu quả với chi phí tối ưu nhất.",
    aboutCardDesc2:
      "Trở thành công ty công nghệ hàng đầu tại Việt Nam, vươn tầm quốc tế.",
    aboutCardDesc3:
      "Đổi mới sáng tạo - Chất lượng vượt trội - Tận tâm với khách hàng.",
    servicesTitle: "Dịch vụ của chúng tôi",
    servicesDesc:
      "Chúng tôi cung cấp đa dạng các dịch vụ công nghệ đáp ứng mọi nhu cầu của doanh nghiệp",
    servicesCardTitle1: "Phát triển ứng dụng",
    servicesCardTitle2: "Ứng dụng di dộng",
    servicesCardTitle3: "Thiết kế UI/UX",
    servicesCardTitle4: "Giải pháp đám mây",
    servicesCardTitle5: "AI & Học máy",
    servicesCardTitle6: "Hỗ trợ kỹ thuật",
    servicesCardDesc1:
      "Xây dựng các giải pháp phần mềm, phù hợp với yêu cầu của từng doanh nghiệp.",
    servicesCardDesc2:
      "Phát triển ứng dụng di động đa nền tảng với trải nghiệm người dùng xuất sắc.",
    servicesCardDesc3:
      "Thiết kế giao diện tinh tế và trải nghiệm người dùng tối ưu cho sản phẩm của bạn.",
    servicesCardDesc4:
      "Tư vấn và triển khai hệ thống điện toán đám mây, giúp doanh nghiệp vận hành hiệu quả.",
    servicesCardDesc5:
      "Ứng dụng trí tuệ nhân tạo nhằm tự động hóa và tối ưu hóa quy trình kinh doanh.",
    servicesCardDesc6:
      "Dịch vụ hỗ trợ 24/7 với đội ngũ kỹ thuật viên giàu kinh nghiệm.",
    servicesMore: "Xem thêm",
    technologiesTitle: "Công nghệ sử dụng",
    mileStone1: "Dự án hoàn thành",
    mileStone2: "Khách hàng hài lòng",
    mileStone3: "Nhân sự",
    mileStone4: "Năm kinh nghiệm",
    projectTitle: "Dự án",
    projectAll: "Xem tất cả",
    projectDescription: "Đây là một số dự án tiêu biểu đã phát triển, thể hiện kinh nghiệm của chúng tôi trong việc xây dựng các ứng dụng web hiện đại.",
    projectCardTitle1: "Hệ thống quản lý doanh nghiệp",
    projectCardTitle2: "Ứng dụng giao đồ ăn nhanh",
    projectCardTitle3: "Trang thương mại điện tử",
    projectCardTitle4: "Travel review site",
    projectCardDesc1:
      "Giải pháp web tối ưu giúp doanh nghiệp quản lý và vận hành nguồn lực thông minh.",
    projectCardDesc2:
      "Ứng dụng di động tinh gọn mang đến trải nghiệm đặt món nhanh chóng và tiện lợi.",
    projectCardDesc3:
      "Nền tảng mua sắm trực tuyến hiện đại, mang lại hành trình khám phá sản phẩm mượt mà.",
    projectCardDesc4: "Trang đánh giá địa điểm du lịch.",
    testimonialsTitle: "Được khách hàng tin tưởng và lựa chọn",
    testimonialsCardName1: "Trần Thu Hà",
    testimonialsCardName2: "Nguyễn Minh Quân",
    testimonialsCardName3: "Dương Quốc Hưng",
    testimonialsCardName4: "Phạm Ngọc Anh",
    TestimonialsCardTitle1: "Giám đốc điều hành Công ty Vincentimo",
    TestimonialsCardTitle2: "Trưởng phòng Kinh doanh Công ty Duy Nhất Tech",
    TestimonialsCardTitle3: "Giám đốc kỹ thuật Công ty giải trí Duong Hung",
    TestimonialsCardTitle4: "Người sáng lập Học Viện Ngôi sao trẻ",
    TestimonailsCardText1:
      "Dịch vụ của DUDI Software đã giúp chúng tôi số hóa hoạt động một cách thành công. Đội ngũ làm việc chuyên nghiệp và luôn nhiệt tình hỗ trợ.",
    TestimonailsCardText2:
      "Ứng dụng do DUDI phát triển đã giúp chúng tôi tăng doanh thu. Giao diện đẹp, dễ sử dụng và hoạt động rất ổn định.",

    TestimonailsCardText3:
      "Trải nghiệm hợp tác tuyệt vời! Các kỹ sư của họ có chuyên môn cao, giao tiếp tốt và luôn bàn giao đúng tiến độ.",

    TestimonailsCardText4:
      "Chúng tôi hoàn toàn hài lòng với ứng dụng di động. DUDI Software thực sự thấu hiểu trải nghiệm người dùng.",
    contactTitle: "Liên hệ với chúng tôi",
    contactAddressTitle: "Địa chỉ",
    contactAddress1:
      "232 Đường Nguyễn Thị Minh Khai, phường Xuân Hòa, TP.Hồ Chí Minh",

    contactAddress2:
      "49/2 Đường 14, Phường Thủ Đức, TP.Hồ Chí Minh",
    infoTitle: "Liên hệ",
    hourTitle: "Giờ làm việc",
    hourText: "Thứ hai - Thứ 6: 9AM - 6PM",
    scanText: "Quét để liên hệ nhanh",
    formInstruct:
      "Hãy để lại thông tin của bạn, chúng tôi sẽ liên hệ sớm nhất có thể",
    formName: "Tên đầy đủ *",
    formSubject: "Chủ đề",
    formMessage: "Nội dung *",
    formButton: "Gửi",
    footerText:
      "Công ty phần mềm hàng đầu với các giải pháp công nghệ hiện đại và sáng tạo, giúp doanh nghiệp phát triển bền vững.",
    footerRight: "© 2023 DUDI Software. Bảo lưu mọi quyền.",
    footerRight1: "Chính sách bảo mật",
    footerRight2: "Điều khoản sử dụng",
    portfolioDetailTitle: "Dự án nổi bật",
    portfolioButtonPrev: "Trước",
    portfolioButtonNext: "Sau",
    portfolioSearch: "Tìm kiếm",
    projectsPageTitle: "Dự án nổi bật",
    projectsFilter: "BỘ LỌC",
    projectsSortBy: "Sắp xếp theo:",
    projectsSortNewest: "Mới nhất",
    projectsSortOldest: "Cũ nhất",
    projectsSearchResult: "Kết quả tìm kiếm:",
    projectsNoResult: "Không tìm thấy kết quả cho",
    projectsNoMatch: "Không tìm thấy project nào phù hợp",
    projectsMore: "Xem thêm",
    projectsReachUs: "Liên hệ",
    projectsReachSubtitle: "Hãy để lại thông tin của bạn, chúng tôi sẽ liên hệ sớm nhất có thể",
    projectsScanQR: "Quét để liên hệ nhanh",
    projectsName: "Tên",
    projectsEmail: "Email",
    projectsSubject: "Chủ đề",
    projectsMessage: "Nội dung",
    // Categories
    catAll: "Tất cả",
    cat1: "Mẫu website bán hàng",
    cat2: "Mẫu website doanh nghiệp",
    cat3: "Mẫu website giới thiệu dịch vụ",
    cat4: "Mẫu website thương mại điện tử",
    cat5: "Mẫu website mỹ phẩm",
    cat6: "Mẫu website nội thất",
    cat7: "Mẫu website bất động sản",
    cat8: "Mẫu website nhà hàng",
    cat9: "Mẫu website khách sạn",
    cat10: "Mẫu website du lịch",
    cat11: "Mẫu website spa – thẩm mỹ",
    cat12: "Mẫu website phòng khám",
    cat13: "Mẫu website giáo dục – đào tạo",
    cat14: "Mẫu website trung tâm ngoại ngữ",
    cat15: "Mẫu website tin tức – blog",
    cat16: "Mẫu website cá nhân – portfolio",
    cat17: "Mẫu website startup",
    cat18: "Mẫu website landing page",
    cat19: "Mẫu website sự kiện",
    cat20: "Mẫu website tuyển dụng",
    cat21: "Mẫu website công nghệ",
    cat22: "Mẫu website điện thoại",
    cat23: "Mẫu website máy tính",
    cat24: "Mẫu website phần mềm",
    // Project Titles (Vietnamese)
    projTitle1: "Yoga & Trung tâm Wellness",
    projTitle2: "SaiGonDi - Du lịch & Khám phá",
    projTitle3: "Dudi Credit - Dịch vụ Tài chính",
    projTitle4: "MoneyWise - Quản lý chi tiêu",
    projTitle5: "Hệ thống Nhà hàng Cao cấp",
    projTitle6: "Công ty Luật ANP",
    projTitle7: "Cổng Bất động sản Sigma",
    projTitle8: "Cửa hàng Linh kiện PC & Dịch vụ",
    projTitle9: "Sàn thương mại đa nhà cung cấp",
    projTitle10: "Nền tảng thương mại toàn cầu",
    projTitle11: "Chợ sản phẩm làm đẹp",
    projTitle12: "Cửa hàng chăm sóc da",
    projTitle13: "Cửa hàng nội thất",
    projTitle14: "Bộ sưu tập trang trí nhà",
    projTitle15: "Cổng bất động sản",
    projTitle16: "Tìm kiếm bất động sản cao cấp",
    projTitle17: "Quản lý quán cà phê",
    projTitle18: "Trung tâm cà phê đặc biệt",
    projTitle19: "Hệ thống đặt phòng khách sạn",
    projTitle20: "Mạng lưới khách sạn boutique",
    projTitle21: "Website đại lý du lịch",
    projTitle22: "Đặt tour mạo hiểm",
    projTitle23: "Ứng dụng đặt lịch dịch vụ",
    projTitle24: "Cổng trung tâm chăm sóc sức khỏe",
    projTitle25: "Cổng phòng khám y tế",
    projTitle26: "Website phòng khám nha khoa",
    projTitle27: "Nền tảng học trực tuyến",
    projTitle28: "Viện đào tạo chuyên nghiệp",
    projTitle29: "Trung tâm học ngôn ngữ",
    projTitle30: "Học viện tiếng Anh trực tuyến",
    projTitle31: "Mạng tin tức & Blog",
    projTitle32: "Cổng tin tức công nghệ",
    projTitle33: "Trưng bày Portfolio",
    projTitle34: "Website Portfolio nhà thiết kế",
    projTitle35: "Pitch Startup công nghệ",
    projTitle36: "Ra mắt nền tảng SaaS",
    projTitle37: "Landing page ra mắt sản phẩm",
    projTitle38: "Trang chuyển đổi chiến dịch",
    projTitle39: "Nền tảng quản lý sự kiện",
    projTitle40: "Cổng việc làm",
    projTitle41: "Nền tảng tuyển dụng cao cấp",
    projTitle42: "Trưng bày sản phẩm công nghệ",
    projTitle43: "Trung tâm giải pháp phần mềm",
    projTitle44: "Cửa hàng điện thoại di động",
    projTitle45: "Cửa hàng phần cứng máy tính",
    projTitle46: "Chợ phần mềm",
    // Project Descriptions (Vietnamese)
    projDesc1: "Hệ thống quản lý Spa, Làm đẹp và Mỹ phẩm chuyên nghiệp.",
    projDesc2: "Nền tảng du lịch và khám phá các địa điểm thú vị tại Sài Gòn.",
    projDesc3: "Nền tảng cho vay tiêu dùng và quản lý tín dụng.",
    projDesc4: "Ứng dụng quản lý tài chính cá nhân và theo dõi chi tiêu thông minh.",
    projDesc5: "Giải pháp quản lý nhà hàng, quán ăn và cà phê hiện đại.",
    projDesc6: "Nền tảng dịch vụ pháp lý và quản lý công ty luật chuyên nghiệp.",
    projDesc7: "Hệ thống niêm yết và quản lý bất động sản cao cấp.",
    projDesc8: "Sàn thương mại điện tử linh kiện máy tính và dịch vụ phần cứng.",
    projDesc9: "Nền tảng kết nối nhiều người bán với người mua toàn quốc.",
    projDesc10: "Nền tảng thương mại điện tử quốc tế với hỗ trợ logistics.",
    projDesc11: "Cửa hàng trực tuyến chuyên về mỹ phẩm và sản phẩm làm đẹp.",
    projDesc12: "Thương hiệu chăm sóc da cao cấp với gợi ý sản phẩm.",
    projDesc13: "Nền tảng thương mại điện tử cho thiết kế nội thất và bán đồ nội thất.",
    projDesc14: "Bộ sưu tập được tuyển chọn về trang trí nhà và đồ nội thất.",
    projDesc15: "Nền tảng danh sách bất động sản với tìm kiếm và bộ lọc nâng cao.",
    projDesc16: "Danh sách bất động sản cao cấp với tour ảo.",
    projDesc17: "Hệ thống POS và chương trình khách hàng thân thiết cho quán cà phê.",
    projDesc18: "Xưởng rang cà phê cao cấp với hệ thống đặt hàng trực tuyến.",
    projDesc19: "Nền tảng đặt phòng với công cụ quản lý khách.",
    projDesc20: "Bộ sưu tập khách sạn boutique sang trọng với trải nghiệm độc đáo.",
    projDesc21: "Nền tảng du lịch với đặt tour và gợi ý.",
    projDesc22: "Các gói thể thao mạo hiểm và phiêu lưu với thông tin an toàn.",
    projDesc23: "Hệ thống đặt lịch hoàn chỉnh cho dịch vụ spa và làm đẹp.",
    projDesc24: "Dịch vụ spa và chăm sóc sức khỏe với hồ sơ chuyên gia.",
    projDesc25: "Hệ thống quản lý y tế với lịch hẹn.",
    projDesc26: "Nền tảng dịch vụ nha khoa với hồ sơ bệnh nhân và thanh toán.",
    projDesc27: "Cung cấp khóa học trực tuyến với theo dõi tiến độ học viên.",
    projDesc28: "Nền tảng đào tạo doanh nghiệp với chương trình chứng chỉ.",
    projDesc29: "Trung tâm đào tạo ngoại ngữ với khóa học tương tác.",
    projDesc30: "Trường tiếng Anh với giảng viên bản ngữ.",
    projDesc31: "Hệ thống quản lý nội dung cho xuất bản và phân phối.",
    projDesc32: "Nền tảng tin tức công nghệ mới nhất và phân tích ngành.",
    projDesc33: "Website portfolio cá nhân cho các chuyên gia sáng tạo.",
    projDesc34: "Portfolio nghệ thuật với thư viện dự án và đánh giá khách hàng.",
    projDesc35: "Website startup với pitch nhà đầu tư và demo sản phẩm.",
    projDesc36: "Nền tảng phần mềm dịch vụ với dùng thử và bảng giá.",
    projDesc37: "Landing page chuyển đổi cao cho ra mắt sản phẩm.",
    projDesc38: "Landing page tối ưu cho các chiến dịch marketing.",
    projDesc39: "Quản lý sự kiện hoàn chỉnh với bán vé và đăng ký.",
    projDesc40: "Nền tảng tuyển dụng kết nối nhà tuyển dụng và người tìm việc.",
    projDesc41: "Dịch vụ tuyển dụng cao cấp cho các vị trí quản lý cấp cao.",
    projDesc42: "Danh mục sản phẩm cho các công ty và nhà bán lẻ công nghệ.",
    projDesc43: "Giải pháp phần mềm doanh nghiệp với tài liệu kỹ thuật.",
    projDesc44: "Điện thoại thông minh và thiết bị di động mới nhất với thông số.",
    projDesc45: "Linh kiện máy tính và thiết bị ngoại vi với thông số kỹ thuật.",
    projDesc46: "Nền tảng phân phối phần mềm số với giấy phép.",
    recruitmentTitle: "Tham gia ngay",
    recruitmentDes:
      "Tìm kiếm những tài năng trẻ đầy đam mê để cùng tạo nên các giải pháp công nghệ hiện đại.",
    job1: "Thực tập Full-stack",
    job2: "Thực tập Sale",
    jobLocation1: "HCM, Việt Nam",
    jobLocation2: "HCM, Việt Nam",
    jobDesc1:
      "DUDI Software đang tìm kiếm một Thực tập sinh Lập trình viên Full-stack nhiệt huyết để gia nhập đội ngũ. Bạn sẽ tham gia phát triển cả tính năng front-end và back-end, học hỏi công nghệ hiện đại và làm việc cùng các lập trình viên giàu kinh nghiệm trong dự án thực tế.",
    jobDesc2:
      "DUDI Software đang tìm kiếm một Thực tập sinh Sale năng động để hỗ trợ đội ngũ phát triển kinh doanh. Bạn sẽ tham gia tìm kiếm khách hàng tiềm năng, chuẩn bị bài thuyết trình, hỗ trợ giao tiếp với đối tác và có cơ hội trải nghiệm thực tế trong lĩnh vực phần mềm.",
    jobButton: "Ứng tuyển",
  },
};

export type TranslationKey = keyof (typeof translations)["en"];

type Lang = "en" | "vi";
interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("vi");

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: keyof (typeof translations)["en"]) => translations[lang][key];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext)!;
